name: Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        description: "Choose the build status for the demo"
        required: true  
        type: string  
        default: failed

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.builder.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_PATH 

      - name: Build
        id: build
        run: echo "status=${{ inputs.builder_status }}" >> "$GITHUB_OUTPUT"  


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploy"

      
